### PR TITLE
pusi :heart:

### PR DESCRIPTION
**Pull request by sinjs**

### CODE REVIEW

**Comment by sinjs** [comment]
merge

**Comment by sinjs** [comment]
merge

**Comment by sinjs** [comment]
merge

**Comment by sinjs** [comment]
merge

**Comment by sinjs** [comment]
merge

**Comment by sinjs** [comment]
merge

**Comment by aeroplaneticdos** [comment]
agreed
merge

**Comment by cedkim** [comment]
duplicate of #gayporn

**Comment by aeroplaneticdos** [comment]
:(

**Pull request closed without merging**
